services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: postgres:16-pgvector
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DB_HOST_PORT:-5432}:5432"
    networks:
      - gestbd_net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    ports:
      - "${PGADMIN_HOST_PORT:-8080}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - gestbd_net

  graphdb:
    image: ontotext/graphdb:10.3.2
    ports:
      - 8000:7200
    environment:
      GDB_JAVA_OPTS: -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
    volumes:
      - graphdb_data:/opt/graphdb/home
    networks:
      - gestbd_net

volumes:
  db_data:
  pgadmin_data:
  graphdb_data:

networks:
  gestbd_net:
    external: true
